/**
 * SINGLE SOURCE OF TRUTH — Topics
 * IDs are stable kebab strings: `{subject_id}:{topic-slug}`
 * These are LOCAL reference IDs. The DB topics.id is a UUID generated by Postgres.
 * resolveTopicId() bridges: local-id/title → DB UUID via title lookup.
 */
export interface TopicDef {
  id: string;         // local stable reference ID
  subject_id: string; // must match a SubjectDef.id
  title: string;      // exact title stored in DB topics.title
  form_level?: string;
  sort_order: number;
  subtopics?: string[];
}

export const TOPICS: TopicDef[] = [
  // ── Mathematics (hs-math) ──────────────────────────────────────────────
  { id: 'hs-math:algebra',          subject_id: 'hs-math', title: 'Algebra',              sort_order: 1,  subtopics: ['Linear Equations','Quadratic Equations','Simultaneous Equations','Inequalities','Sequences and Series','Logarithms','Indices'] },
  { id: 'hs-math:geometry',         subject_id: 'hs-math', title: 'Geometry',             sort_order: 2,  subtopics: ['Angles and Triangles','Circles','Transformations','Congruence and Similarity','Area and Perimeter','Volume and Surface Area'] },
  { id: 'hs-math:trigonometry',     subject_id: 'hs-math', title: 'Trigonometry',         sort_order: 3,  subtopics: ['Trigonometric Ratios','Trigonometric Identities','Solving Triangles','Bearings','Angles of Elevation and Depression'] },
  { id: 'hs-math:statistics',       subject_id: 'hs-math', title: 'Statistics',           sort_order: 4,  subtopics: ['Data Collection and Organization','Measures of Central Tendency','Measures of Dispersion','Probability','Frequency Distributions'] },
  { id: 'hs-math:numbers',          subject_id: 'hs-math', title: 'Numbers',              sort_order: 5,  subtopics: ['Integers','Fractions and Decimals','Percentages','Ratio and Proportion','Rates and Variations'] },
  { id: 'hs-math:calculus',         subject_id: 'hs-math', title: 'Calculus',             sort_order: 6,  subtopics: ['Differentiation','Integration','Applications of Calculus'] },

  // ── Physics (hs-physics) ───────────────────────────────────────────────
  { id: 'hs-physics:mechanics',     subject_id: 'hs-physics', title: 'Mechanics',         sort_order: 1,  subtopics: ['Motion','Force and Momentum','Energy','Work Power and Machines','Pressure'] },
  { id: 'hs-physics:waves',         subject_id: 'hs-physics', title: 'Waves',             sort_order: 2,  subtopics: ['Wave Motion','Sound Waves','Light Waves','Electromagnetic Spectrum'] },
  { id: 'hs-physics:electricity',   subject_id: 'hs-physics', title: 'Electricity',       sort_order: 3,  subtopics: ['Electric Circuits','Ohms Law','Electrical Energy and Power','Electromagnetism'] },
  { id: 'hs-physics:heat',          subject_id: 'hs-physics', title: 'Heat',              sort_order: 4,  subtopics: ['Temperature and Heat','Thermal Expansion','Heat Transfer','Specific Heat Capacity','Latent Heat'] },
  { id: 'hs-physics:optics',        subject_id: 'hs-physics', title: 'Optics',            sort_order: 5,  subtopics: ['Reflection','Refraction','Lenses','Optical Instruments'] },

  // ── Chemistry (hs-chemistry) ───────────────────────────────────────────
  { id: 'hs-chemistry:atomic',      subject_id: 'hs-chemistry', title: 'Atomic Structure',      sort_order: 1, subtopics: ['Elements and Compounds','Electronic Configuration','Periodic Table','Chemical Bonding'] },
  { id: 'hs-chemistry:reactions',   subject_id: 'hs-chemistry', title: 'Chemical Reactions',    sort_order: 2, subtopics: ['Chemical Equations','Types of Reactions','Redox Reactions','Reaction Rates'] },
  { id: 'hs-chemistry:acids-bases', subject_id: 'hs-chemistry', title: 'Acids and Bases',       sort_order: 3, subtopics: ['Properties of Acids and Bases','pH Scale','Neutralization','Salts'] },
  { id: 'hs-chemistry:organic',     subject_id: 'hs-chemistry', title: 'Organic Chemistry',     sort_order: 4, subtopics: ['Hydrocarbons','Alcohols','Carboxylic Acids','Esters','Polymers'] },
  { id: 'hs-chemistry:electrolysis',subject_id: 'hs-chemistry', title: 'Electrolysis',          sort_order: 5, subtopics: ['Electrolytes','Laws of Electrolysis','Electroplating','Industrial Applications'] },

  // ── Biology (hs-biology) ───────────────────────────────────────────────
  { id: 'hs-biology:cell-biology',  subject_id: 'hs-biology', title: 'Cell Biology',      sort_order: 1, subtopics: ['Cell Structure','Cell Division','Cell Transport','Enzymes','Cellular Respiration'] },
  { id: 'hs-biology:nutrition',     subject_id: 'hs-biology', title: 'Nutrition',         sort_order: 2, subtopics: ['Balanced Diet','Vitamins and Minerals','Digestion','Absorption'] },
  { id: 'hs-biology:respiration',   subject_id: 'hs-biology', title: 'Respiration',       sort_order: 3, subtopics: ['Aerobic Respiration','Anaerobic Respiration','Gas Exchange','Breathing Mechanisms'] },
  { id: 'hs-biology:reproduction',  subject_id: 'hs-biology', title: 'Reproduction',      sort_order: 4, subtopics: ['Sexual Reproduction','Asexual Reproduction','Human Reproductive System','Plant Reproduction'] },
  { id: 'hs-biology:genetics',      subject_id: 'hs-biology', title: 'Genetics',          sort_order: 5, subtopics: ['Inheritance','Mendels Laws','Variation','Genetic Disorders','DNA and RNA'] },

  // ── English (hs-english) ───────────────────────────────────────────────
  { id: 'hs-english:grammar',       subject_id: 'hs-english', title: 'Grammar',           sort_order: 1, subtopics: ['Parts of Speech','Tenses','Subject-Verb Agreement','Direct and Indirect Speech'] },
  { id: 'hs-english:composition',   subject_id: 'hs-english', title: 'Composition',       sort_order: 2, subtopics: ['Essay Writing','Creative Writing','Letter Writing','Summary Writing','Comprehension'] },
  { id: 'hs-english:poetry',        subject_id: 'hs-english', title: 'Poetry',            sort_order: 3, subtopics: ['Poetic Devices','Analysis of Poems','Poetic Forms'] },
  { id: 'hs-english:literature',    subject_id: 'hs-english', title: 'Literature',        sort_order: 4, subtopics: ['Novels','Short Stories','Drama','Character Analysis','Themes and Motifs'] },

  // ── Kiswahili (hs-kiswahili) ───────────────────────────────────────────
  { id: 'hs-kiswahili:sarufi',      subject_id: 'hs-kiswahili', title: 'Sarufi',          sort_order: 1, subtopics: ['Viwakilishi','Vitenzi','Mahusiano','Jina'] },
  { id: 'hs-kiswahili:insha',       subject_id: 'hs-kiswahili', title: 'Insha',           sort_order: 2, subtopics: ['Insha ya kueleza','Insha ya kubuni','Barua','Muhtasari'] },
  { id: 'hs-kiswahili:fasihi',      subject_id: 'hs-kiswahili', title: 'Fasihi',          sort_order: 3, subtopics: ['Hadithi fupi','Riwaya','Tamthilia','Mashairi'] },

  // ── History (hs-history) ───────────────────────────────────────────────
  { id: 'hs-history:pre-colonial',  subject_id: 'hs-history', title: 'Pre-Colonial Kenya',  sort_order: 1, subtopics: ['Early Man','Bantu Migration','Coastal Settlements','Trade and Commerce'] },
  { id: 'hs-history:colonial',      subject_id: 'hs-history', title: 'Colonial Period',     sort_order: 2, subtopics: ['Scramble for Africa','Establishment of British Rule','Resistance Movements'] },
  { id: 'hs-history:independence',  subject_id: 'hs-history', title: 'Independence',        sort_order: 3, subtopics: ['Rise of Nationalism','Mau Mau Uprising','Negotiations for Independence'] },
  { id: 'hs-history:post-independence', subject_id: 'hs-history', title: 'Post-Independence', sort_order: 4, subtopics: ['Jomo Kenyatta Era','Daniel arap Moi Era','Devolution'] },

  // ── Geography (hs-geography) ───────────────────────────────────────────
  { id: 'hs-geography:physical',    subject_id: 'hs-geography', title: 'Physical Geography', sort_order: 1, subtopics: ['Earth Structure','Weather and Climate','Rivers and Lakes','Natural Vegetation'] },
  { id: 'hs-geography:human',       subject_id: 'hs-geography', title: 'Human Geography',   sort_order: 2, subtopics: ['Population','Settlement','Agriculture','Industry','Trade and Transport'] },
  { id: 'hs-geography:map-work',    subject_id: 'hs-geography', title: 'Map Work',          sort_order: 3, subtopics: ['Reading Maps','Scale and Direction','Interpretation','Topographical Maps'] },

  // ── Business Studies (hs-business) ────────────────────────────────────
  { id: 'hs-business:forms',        subject_id: 'hs-business', title: 'Business Forms',    sort_order: 1, subtopics: ['Sole Proprietorship','Partnerships','Companies','Cooperatives'] },
  { id: 'hs-business:finance',      subject_id: 'hs-business', title: 'Finance',           sort_order: 2, subtopics: ['Sources of Capital','Budgeting','Financial Statements','Banking','Insurance'] },
  { id: 'hs-business:marketing',    subject_id: 'hs-business', title: 'Marketing',         sort_order: 3, subtopics: ['Market Research','Marketing Mix','Advertising','Distribution'] },

  // ── CRE (hs-cre) ───────────────────────────────────────────────────────
  { id: 'hs-cre:old-testament',     subject_id: 'hs-cre', title: 'Old Testament',         sort_order: 1, subtopics: ['Creation','Patriarchs','Moses and Exodus','Prophets'] },
  { id: 'hs-cre:new-testament',     subject_id: 'hs-cre', title: 'New Testament',         sort_order: 2, subtopics: ['Life of Jesus','Parables','Miracles','Epistles','Early Church'] },
  { id: 'hs-cre:christian-living',  subject_id: 'hs-cre', title: 'Christian Living',      sort_order: 3, subtopics: ['Faith and Works','Discipleship','Morality','Social Responsibility'] },

  // ── Technical Drawing (hs-technical) ───────────────────────────────────
  { id: 'hs-technical:geometric',   subject_id: 'hs-technical', title: 'Geometric Drawing',  sort_order: 1, subtopics: ['Lines and Angles','Polygons','Circles and Arcs','Tangency'] },
  { id: 'hs-technical:projections', subject_id: 'hs-technical', title: 'Projections',        sort_order: 2, subtopics: ['Orthographic Projection','Isometric Projection','Oblique Projection'] },
  { id: 'hs-technical:building',    subject_id: 'hs-technical', title: 'Building Drawing',   sort_order: 3, subtopics: ['Plans and Elevations','Site Plans','Foundation Plans'] },

  // ── Computer Studies (hs-computer) ─────────────────────────────────────
  { id: 'hs-computer:hardware',     subject_id: 'hs-computer', title: 'Hardware',          sort_order: 1, subtopics: ['Computer Systems','Input Devices','Output Devices','Storage Devices'] },
  { id: 'hs-computer:software',     subject_id: 'hs-computer', title: 'Software',          sort_order: 2, subtopics: ['Operating Systems','Application Software','Programming Basics','Spreadsheets'] },
  { id: 'hs-computer:networks',     subject_id: 'hs-computer', title: 'Networks',          sort_order: 3, subtopics: ['Data Communication','Internet','Security','E-commerce'] },

  // ── Agriculture (hs-agriculture) ───────────────────────────────────────
  { id: 'hs-agriculture:crop',      subject_id: 'hs-agriculture', title: 'Crop Production',   sort_order: 1, subtopics: ['Crop Classification','Land Preparation','Planting','Crop Management','Harvesting'] },
  { id: 'hs-agriculture:animal',    subject_id: 'hs-agriculture', title: 'Animal Production', sort_order: 2, subtopics: ['Livestock Rearing','Poultry','Dairy Farming','Animal Health','Breeding'] },
  { id: 'hs-agriculture:soil',      subject_id: 'hs-agriculture', title: 'Soil Science',      sort_order: 3, subtopics: ['Soil Formation','Soil Types','Soil Fertility','Irrigation','Drainage'] },

  // ── Home Science (hs-home-science) ─────────────────────────────────────
  { id: 'hs-home-science:nutrition',subject_id: 'hs-home-science', title: 'Nutrition and Cooking', sort_order: 1, subtopics: ['Food Groups','Meal Planning','Food Preservation','Cooking Methods'] },
  { id: 'hs-home-science:textiles', subject_id: 'hs-home-science', title: 'Textiles',              sort_order: 2, subtopics: ['Fabric Types','Sewing Techniques','Pattern Making','Clothing Care'] },
  { id: 'hs-home-science:childcare',subject_id: 'hs-home-science', title: 'Child Care',            sort_order: 3, subtopics: ['Child Development','Nutrition','Health','Play and Learning','Safety'] },

  // ── University — Engineering (uni-engineering) ─────────────────────────
  { id: 'uni-engineering:calculus',       subject_id: 'uni-engineering', title: 'Calculus I',            sort_order: 1 },
  { id: 'uni-engineering:circuits',       subject_id: 'uni-engineering', title: 'Circuit Theory',        sort_order: 2 },
  { id: 'uni-engineering:mechanics',      subject_id: 'uni-engineering', title: 'Mechanics',             sort_order: 3 },
  { id: 'uni-engineering:materials',      subject_id: 'uni-engineering', title: 'Material Science',      sort_order: 4 },
  { id: 'uni-engineering:ethics',         subject_id: 'uni-engineering', title: 'Engineering Ethics',    sort_order: 5 },

  // ── University — Computer Science (uni-computer-science) ───────────────
  { id: 'uni-cs:discrete-math',           subject_id: 'uni-computer-science', title: 'Discrete Mathematics',     sort_order: 1 },
  { id: 'uni-cs:programming',             subject_id: 'uni-computer-science', title: 'Programming I (Python)',    sort_order: 2 },
  { id: 'uni-cs:data-structures',         subject_id: 'uni-computer-science', title: 'Data Structures and Algorithms', sort_order: 3 },
  { id: 'uni-cs:digital-logic',           subject_id: 'uni-computer-science', title: 'Digital Logic',            sort_order: 4 },
  { id: 'uni-cs:databases',               subject_id: 'uni-computer-science', title: 'Databases and SQL',        sort_order: 5 },

  // ── University — Medicine (uni-medicine) ───────────────────────────────
  { id: 'uni-medicine:anatomy',           subject_id: 'uni-medicine', title: 'Human Anatomy I',              sort_order: 1 },
  { id: 'uni-medicine:biochemistry',      subject_id: 'uni-medicine', title: 'Medical Biochemistry',         sort_order: 2 },
  { id: 'uni-medicine:physiology',        subject_id: 'uni-medicine', title: 'Medical Physiology',           sort_order: 3 },
  { id: 'uni-medicine:cell-biology',      subject_id: 'uni-medicine', title: 'Cell Biology',                 sort_order: 4 },
  { id: 'uni-medicine:clinical-intro',    subject_id: 'uni-medicine', title: 'Introduction to Clinical Medicine', sort_order: 5 },

  // ── Self-Directed — Automotive Engineering (sd-automotive) ────────────
  { id: 'sd-automotive:ice-basics',       subject_id: 'sd-automotive', title: 'Internal Combustion Engines',   sort_order: 1 },
  { id: 'sd-automotive:ev-systems',       subject_id: 'sd-automotive', title: 'Electric Vehicle Systems',      sort_order: 2 },
  { id: 'sd-automotive:fuel-systems',     subject_id: 'sd-automotive', title: 'Fuel Systems and Injection',    sort_order: 3 },
  { id: 'sd-automotive:engine-mgmt',      subject_id: 'sd-automotive', title: 'Engine Management Systems',     sort_order: 4 },
  { id: 'sd-automotive:diagnostics',      subject_id: 'sd-automotive', title: 'Vehicle Diagnostics and OBD',   sort_order: 5 },
  { id: 'sd-automotive:thermodynamics',   subject_id: 'sd-automotive', title: 'Thermodynamics',               sort_order: 6 },
  { id: 'sd-automotive:electrical',       subject_id: 'sd-automotive', title: 'Electrical Systems and Electronics', sort_order: 7 },
  { id: 'sd-automotive:chassis',          subject_id: 'sd-automotive', title: 'Chassis Dynamics and Suspension', sort_order: 8 },
  { id: 'sd-automotive:tuning',           subject_id: 'sd-automotive', title: 'Performance Tuning Fundamentals', sort_order: 9 },

  // ── Self-Directed — Computer Science Pro (sd-computer-science) ─────────
  { id: 'sd-cs:intro-programming',        subject_id: 'sd-computer-science', title: 'Introduction to Programming',      sort_order: 1 },
  { id: 'sd-cs:data-structures',          subject_id: 'sd-computer-science', title: 'Data Structures and Algorithms',   sort_order: 2 },
  { id: 'sd-cs:oop',                       subject_id: 'sd-computer-science', title: 'Object-Oriented Programming',      sort_order: 3 },
  { id: 'sd-cs:databases',                subject_id: 'sd-computer-science', title: 'Databases and SQL',                sort_order: 4 },
  { id: 'sd-cs:networking',               subject_id: 'sd-computer-science', title: 'Networking Fundamentals',          sort_order: 5 },
  { id: 'sd-cs:web-dev',                  subject_id: 'sd-computer-science', title: 'Web Development Basics',           sort_order: 6 },
  { id: 'sd-cs:apis',                     subject_id: 'sd-computer-science', title: 'APIs and Backend Development',     sort_order: 7 },
  { id: 'sd-cs:git',                      subject_id: 'sd-computer-science', title: 'Version Control with Git',         sort_order: 8 },
  { id: 'sd-cs:system-design',            subject_id: 'sd-computer-science', title: 'System Design Fundamentals',       sort_order: 9 },
];

/** Get all topics for a given subject_id. */
export const getTopicsBySubject = (subjectId: string): TopicDef[] =>
  TOPICS.filter((t) => t.subject_id === subjectId);

/** Look up a topic by its local stable ID. */
export const getTopicById = (id: string): TopicDef | undefined =>
  TOPICS.find((t) => t.id === id);
