version: '3.8'

services:
  easytutor-web:
    build: .
    container_name: easytutor-web
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
